In [1]:
# Importing Usefull libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-0.22-cp37-none-manylinux1_x86_64.whl (64.4 MB)
     |█████████████████▉              | 35.8 MB 1.2 MB/s eta 0:00:25

In [0]:
# Loading our data
train = pd.read_csv("Train.csv")
test = pd.read_csv("Test.csv")
ss = pd.read_csv("SampleSubmission.csv")

In [27]:
train.head()
train.shape

(30557, 85)

In [28]:
test.head()
test.shape
# ss.head()

(16136, 77)

In [29]:
train.describe()

             target    target_min  ...         Month           Day
count  30557.000000  30557.000000  ...  30557.000000  30557.000000
mean      61.148045     29.025866  ...      2.095755     15.254312
std       46.861309     33.119775  ...      0.899081      8.921199
min        1.000000      1.000000  ...      1.000000      1.000000
25%       25.000000      5.000000  ...      1.000000      7.000000
50%       50.000000     15.000000  ...      2.000000     15.000000
75%       80.000000     44.000000  ...      3.000000     23.000000
max      815.000000    438.000000  ...      4.000000     31.000000

[8 rows x 82 columns]

In [30]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30557 entries, 0 to 30556
Data columns (total 85 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      30557 non-null  object
 1   Date                                                 30557 non-null  object
 2   Place_ID                                             30557 non-null  object
 3   target                                               30557 non-null  float64
 4   target_min                                           30557 non-null  float64
 5   target_max                                           30557 non-null  float64
 6   target_variance                                      30557 non-null  float64
 7   target_count                                         30557 non-null  int64
 8   precipitable_water_entire_atmosphere                 30557 non-null  float64
 9   relative_humidity_2m_above_ground                    30557 non-null  float64
 10  specific_humidity_2m_above_ground                    30557 non-null  float64
 11  temperature_2m_above_ground                          30557 non-null  float64
 12  u_component_of_wind_10m_above_ground                 30557 non-null  float64
 13  v_component_of_wind_10m_above_ground                 30557 non-null  float64
 14  L3_NO2_NO2_column_number_density                     30557 non-null  float64
 15  L3_NO2_NO2_slant_column_number_density               30557 non-null  float64
 16  L3_NO2_absorbing_aerosol_index                       30557 non-null  float64
 17  L3_NO2_cloud_fraction                                30557 non-null  float64
 18  L3_NO2_sensor_altitude                               30557 non-null  float64
 19  L3_NO2_sensor_azimuth_angle                          30557 non-null  float64
 20  L3_NO2_sensor_zenith_angle                           30557 non-null  float64
 21  L3_NO2_solar_azimuth_angle                           30557 non-null  float64
 22  L3_NO2_solar_zenith_angle                            30557 non-null  float64
 23  L3_NO2_stratospheric_NO2_column_number_density       30557 non-null  float64
 24  L3_NO2_tropopause_pressure                           30557 non-null  float64
 25  L3_NO2_tropospheric_NO2_column_number_density        30557 non-null  float64
 26  L3_O3_O3_column_number_density                       30557 non-null  float64
 27  L3_O3_O3_effective_temperature                       30557 non-null  float64
 28  L3_O3_cloud_fraction                                 30557 non-null  float64
 29  L3_O3_sensor_azimuth_angle                           30557 non-null  float64
 30  L3_O3_sensor_zenith_angle                            30557 non-null  float64
 31  L3_O3_solar_azimuth_angle                            30557 non-null  float64
 32  L3_O3_solar_zenith_angle                             30557 non-null  float64
 33  L3_CO_CO_column_number_density                       30557 non-null  float64
 34  L3_CO_H2O_column_number_density                      30557 non-null  float64
 35  L3_CO_cloud_height                                   30557 non-null  float64
 36  L3_CO_sensor_altitude                                30557 non-null  float64
 37  L3_CO_sensor_azimuth_angle                           30557 non-null  float64
 38  L3_CO_sensor_zenith_angle                            30557 non-null  float64
 39  L3_CO_solar_azimuth_angle                            30557 non-null  float64
 40  L3_CO_solar_zenith_angle                             30557 non-null  float64
 41  L3_HCHO_HCHO_slant_column_number_density             30557 non-null  float64
 42  L3_HCHO_cloud_fraction                               30557 non-null  float64
 43  L3_HCHO_sensor_azimuth_angle                         30557 non-null  float64
 44  L3_HCHO_sensor_zenith_angle                          30557 non-null  float64
 45  L3_HCHO_solar_azimuth_angle                          30557 non-null  float64
 46  L3_HCHO_solar_zenith_angle                           30557 non-null  float64
 47  L3_HCHO_tropospheric_HCHO_column_number_density      30557 non-null  float64
 48  L3_HCHO_tropospheric_HCHO_column_number_density_amf  30557 non-null  float64
 49  L3_CLOUD_cloud_base_height                           30557 non-null  float64
 50  L3_CLOUD_cloud_base_pressure                         30557 non-null  float64
 51  L3_CLOUD_cloud_fraction                              30557 non-null  float64
 52  L3_CLOUD_cloud_optical_depth                         30557 non-null  float64
 53  L3_CLOUD_cloud_top_height                            30557 non-null  float64
 54  L3_CLOUD_cloud_top_pressure                          30557 non-null  float64
 55  L3_CLOUD_sensor_azimuth_angle                        30557 non-null  float64
 56  L3_CLOUD_sensor_zenith_angle                         30557 non-null  float64
 57  L3_CLOUD_solar_azimuth_angle                         30557 non-null  float64
 58  L3_CLOUD_solar_zenith_angle                          30557 non-null  float64
 59  L3_CLOUD_surface_albedo                              30557 non-null  float64
 60  L3_AER_AI_absorbing_aerosol_index                    30557 non-null  float64
 61  L3_AER_AI_sensor_altitude                            30557 non-null  float64
 62  L3_AER_AI_sensor_azimuth_angle                       30557 non-null  float64
 63  L3_AER_AI_sensor_zenith_angle                        30557 non-null  float64
 64  L3_AER_AI_solar_azimuth_angle                        30557 non-null  float64
 65  L3_AER_AI_solar_zenith_angle                         30557 non-null  float64
 66  L3_SO2_SO2_column_number_density                     30557 non-null  float64
 67  L3_SO2_SO2_column_number_density_amf                 30557 non-null  float64
 68  L3_SO2_SO2_slant_column_number_density               30557 non-null  float64
 69  L3_SO2_absorbing_aerosol_index                       30557 non-null  float64
 70  L3_SO2_cloud_fraction                                30557 non-null  float64
 71  L3_SO2_sensor_azimuth_angle                          30557 non-null  float64
 72  L3_SO2_sensor_zenith_angle                           30557 non-null  float64
 73  L3_SO2_solar_azimuth_angle                           30557 non-null  float64
 74  L3_SO2_solar_zenith_angle                            30557 non-null  float64
 75  L3_CH4_CH4_column_volume_mixing_ratio_dry_air        30557 non-null  float64
 76  L3_CH4_aerosol_height                                30557 non-null  float64
 77  L3_CH4_aerosol_optical_depth                         30557 non-null  float64
 78  L3_CH4_sensor_azimuth_angle                          30557 non-null  float64
 79  L3_CH4_sensor_zenith_angle                           30557 non-null  float64
 80  L3_CH4_solar_azimuth_angle                           30557 non-null  float64
 81  L3_CH4_solar_zenith_angle                            30557 non-null  float64
 82  Year                                                 30557 non-null  int64
 83  Month                                                30557 non-null  int64
 84  Day                                                  30557 non-null  int64
dtypes: float64(78), int64(4), object(3)
memory usage: 19.8+ MB

In [31]:
train.isnull().sum().any()

False

In [32]:
train.isnull().sum()

Place_ID X Date               0
Date                          0
Place_ID                      0
target                        0
target_min                    0
                             ..
L3_CH4_solar_azimuth_angle    0
L3_CH4_solar_zenith_angle     0
Year                          0
Month                         0
Day                           0
Length: 85, dtype: int64

In [36]:
# dropping columns not in our test data
for i in train.columns:
  if i not in test.columns:
    print(i)

target = train.target
target.head()

Place_ID X Date
Date
Place_ID
target
target_min
target_max
target_variance
target_count

0    38.0
1    39.0
2    24.0
3    49.0
4    21.0
Name: target, dtype: float64

In [37]:
# splitting our date year and time columns
# Train set
train['Year'] = pd.to_datetime(train['Date']).dt.year
train['Month'] = pd.to_datetime(train['Date']).dt.month
train['Day'] = pd.to_datetime(train['Date']).dt.day

# Test data
test['Year'] = pd.to_datetime(test['Date']).dt.year
test['Month'] = pd.to_datetime(test['Date']).dt.month
test['Day'] = pd.to_datetime(test['Date']).dt.day

KeyError: ignored

In [38]:
# Filling the present null values in the train dataset
train = train.fillna(train.mean())
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30557 entries, 0 to 30556
Data columns (total 85 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Place_ID X Date                                      30557 non-null  object
 1   Date                                                 30557 non-null  object
 2   Place_ID                                             30557 non-null  object
 3   target                                               30557 non-null  float64
 4   target_min                                           30557 non-null  float64
 5   target_max                                           30557 non-null  float64
 6   target_variance                                      30557 non-null  float64
 7   target_count                                         30557 non-null  int64
 8   precipitable_water_entire_atmosphere                 30557 non-null  float64
 9   relative_humidity_2m_above_ground                    30557 non-null  float64
 10  specific_humidity_2m_above_ground                    30557 non-null  float64
 11  temperature_2m_above_ground                          30557 non-null  float64
 12  u_component_of_wind_10m_above_ground                 30557 non-null  float64
 13  v_component_of_wind_10m_above_ground                 30557 non-null  float64
 14  L3_NO2_NO2_column_number_density                     30557 non-null  float64
 15  L3_NO2_NO2_slant_column_number_density               30557 non-null  float64
 16  L3_NO2_absorbing_aerosol_index                       30557 non-null  float64
 17  L3_NO2_cloud_fraction                                30557 non-null  float64
 18  L3_NO2_sensor_altitude                               30557 non-null  float64
 19  L3_NO2_sensor_azimuth_angle                          30557 non-null  float64
 20  L3_NO2_sensor_zenith_angle                           30557 non-null  float64
 21  L3_NO2_solar_azimuth_angle                           30557 non-null  float64
 22  L3_NO2_solar_zenith_angle                            30557 non-null  float64
 23  L3_NO2_stratospheric_NO2_column_number_density       30557 non-null  float64
 24  L3_NO2_tropopause_pressure                           30557 non-null  float64
 25  L3_NO2_tropospheric_NO2_column_number_density        30557 non-null  float64
 26  L3_O3_O3_column_number_density                       30557 non-null  float64
 27  L3_O3_O3_effective_temperature                       30557 non-null  float64
 28  L3_O3_cloud_fraction                                 30557 non-null  float64
 29  L3_O3_sensor_azimuth_angle                           30557 non-null  float64
 30  L3_O3_sensor_zenith_angle                            30557 non-null  float64
 31  L3_O3_solar_azimuth_angle                            30557 non-null  float64
 32  L3_O3_solar_zenith_angle                             30557 non-null  float64
 33  L3_CO_CO_column_number_density                       30557 non-null  float64
 34  L3_CO_H2O_column_number_density                      30557 non-null  float64
 35  L3_CO_cloud_height                                   30557 non-null  float64
 36  L3_CO_sensor_altitude                                30557 non-null  float64
 37  L3_CO_sensor_azimuth_angle                           30557 non-null  float64
 38  L3_CO_sensor_zenith_angle                            30557 non-null  float64
 39  L3_CO_solar_azimuth_angle                            30557 non-null  float64
 40  L3_CO_solar_zenith_angle                             30557 non-null  float64
 41  L3_HCHO_HCHO_slant_column_number_density             30557 non-null  float64
 42  L3_HCHO_cloud_fraction                               30557 non-null  float64
 43  L3_HCHO_sensor_azimuth_angle                         30557 non-null  float64
 44  L3_HCHO_sensor_zenith_angle                          30557 non-null  float64
 45  L3_HCHO_solar_azimuth_angle                          30557 non-null  float64
 46  L3_HCHO_solar_zenith_angle                           30557 non-null  float64
 47  L3_HCHO_tropospheric_HCHO_column_number_density      30557 non-null  float64
 48  L3_HCHO_tropospheric_HCHO_column_number_density_amf  30557 non-null  float64
 49  L3_CLOUD_cloud_base_height                           30557 non-null  float64
 50  L3_CLOUD_cloud_base_pressure                         30557 non-null  float64
 51  L3_CLOUD_cloud_fraction                              30557 non-null  float64
 52  L3_CLOUD_cloud_optical_depth                         30557 non-null  float64
 53  L3_CLOUD_cloud_top_height                            30557 non-null  float64
 54  L3_CLOUD_cloud_top_pressure                          30557 non-null  float64
 55  L3_CLOUD_sensor_azimuth_angle                        30557 non-null  float64
 56  L3_CLOUD_sensor_zenith_angle                         30557 non-null  float64
 57  L3_CLOUD_solar_azimuth_angle                         30557 non-null  float64
 58  L3_CLOUD_solar_zenith_angle                          30557 non-null  float64
 59  L3_CLOUD_surface_albedo                              30557 non-null  float64
 60  L3_AER_AI_absorbing_aerosol_index                    30557 non-null  float64
 61  L3_AER_AI_sensor_altitude                            30557 non-null  float64
 62  L3_AER_AI_sensor_azimuth_angle                       30557 non-null  float64
 63  L3_AER_AI_sensor_zenith_angle                        30557 non-null  float64
 64  L3_AER_AI_solar_azimuth_angle                        30557 non-null  float64
 65  L3_AER_AI_solar_zenith_angle                         30557 non-null  float64
 66  L3_SO2_SO2_column_number_density                     30557 non-null  float64
 67  L3_SO2_SO2_column_number_density_amf                 30557 non-null  float64
 68  L3_SO2_SO2_slant_column_number_density               30557 non-null  float64
 69  L3_SO2_absorbing_aerosol_index                       30557 non-null  float64
 70  L3_SO2_cloud_fraction                                30557 non-null  float64
 71  L3_SO2_sensor_azimuth_angle                          30557 non-null  float64
 72  L3_SO2_sensor_zenith_angle                           30557 non-null  float64
 73  L3_SO2_solar_azimuth_angle                           30557 non-null  float64
 74  L3_SO2_solar_zenith_angle                            30557 non-null  float64
 75  L3_CH4_CH4_column_volume_mixing_ratio_dry_air        30557 non-null  float64
 76  L3_CH4_aerosol_height                                30557 non-null  float64
 77  L3_CH4_aerosol_optical_depth                         30557 non-null  float64
 78  L3_CH4_sensor_azimuth_angle                          30557 non-null  float64
 79  L3_CH4_sensor_zenith_angle                           30557 non-null  float64
 80  L3_CH4_solar_azimuth_angle                           30557 non-null  float64
 81  L3_CH4_solar_zenith_angle                            30557 non-null  float64
 82  Year                                                 30557 non-null  int64
 83  Month                                                30557 non-null  int64
 84  Day                                                  30557 non-null  int64
dtypes: float64(78), int64(4), object(3)
memory usage: 19.8+ MB

In [39]:
train.isnull().sum().any()
train.isnull().sum()

Place_ID X Date               0
Date                          0
Place_ID                      0
target                        0
target_min                    0
                             ..
L3_CH4_solar_azimuth_angle    0
L3_CH4_solar_zenith_angle     0
Year                          0
Month                         0
Day                           0
Length: 85, dtype: int64

In [0]:
# Splitting our data
X= train.drop(["Place_ID X Date", "Date", "Place_ID", "target", "target_min", "target_max", "target_variance", "target_count"], axis=1)
Y = train.target

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_valid, Y_train, Y_valid = train_test_split(X, Y, test_size=0.3, random_state=1) 
# X_train.shape
Y_train.shape

(21389,)

In [0]:
# Modelling using CatBoostRegressor
from catboost import CatBoostRegressor

predictions = []
# predicting using different seeds
for i in range(10):
  model = CatBoostRegressor(verbose=False,
                            depth=9,
                            iterations=1500,
                            random_seed=i)
  model.fit(X, Y)

# making and averaging the predictions
test.drop(["Place_ID X Date", "Date", "Place_ID"], axis=1, inplace=True)
preds=model.predict(test)
predictions.append(preds)
# averaging
predss = np.mean(predictions, axis=0)

In [0]:
# test.drop(["Place_ID X Date", "Date", "Place_ID"], axis=1, inplace=True)
# test.shape
# ss.shape
# test.columns

In [0]:
# making prediction
# preds = model.predict(test)
# preds.shape

In [20]:
ss['target']=predss
ss.head()

        Place_ID X Date     target
0  0OS9LVX X 2020-01-02  31.415238
1  0OS9LVX X 2020-01-03  29.435574
2  0OS9LVX X 2020-01-04  28.168585
3  0OS9LVX X 2020-01-05  34.965844
4  0OS9LVX X 2020-01-06  22.647097

In [0]:
ss.to_csv("sample_sub2.csv", index=False)